apiVersion: v1
kind: Service
metadata:
  labels:
    name: web
  name: web
spec:
  type: LoadBalancer
  ports:
    # The port that this service should serve on.
    - port: 80
      targetPort: 7070
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
     run: web